#!/bin/sh
####################################
# 1wire - Show status of 1-wire temperature sensors
####################################

retval=1

DEVICE_DIR="/sys/bus/w1/devices"

echo

ls -al $DEVICE_DIR/28* 2>/dev/null

num=`ls -al $DEVICE_DIR/28* 2>/dev/null | wc -l`


echo
if [ ""$num"" -lt 1 ]
then
	echo "*NO* 1-wire temperature sensors found!"
	retval=1
else
	echo "$num 1-wire temperature sensors found"
	retval=0
fi

if [ ""$retval"" = 1 ]
#if [ 1 ]
then
	echo
	echo "Attempting recovery..."

	for A in i2c_dev i2c_bcm2835 w1-gpio w1-therm wire cn hwmon
	do
		#sudo rmmod ${A} 2>&1 | grep -v "is not currently loaded"
		sudo rmmod ${A}
	done

	sleep 5

	# WORKING ORDER -
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/i2c/busses/i2c-bcm2835.ko
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/i2c/i2c-dev.ko
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/connector/cn.ko
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/hwmon/hwmon.ko
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/wire.ko
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/masters/w1-gpio.ko gpiopin=5
	#  sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/slaves/w1_therm.ko 

	#    i2c_bcm2835
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/i2c/busses/i2c-bcm2835.ko
	#    i2c_dev
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/i2c/i2c-dev.ko
	#    cn
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/connector/cn.ko
	#    hwmon
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/hwmon/hwmon.ko
	#    wire
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/wire.ko


	# in /boot/config.txt - dtoverlay=w1-gpio,gpiopin=5
	rslt=`sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/masters/w1-gpio.ko gpiopin=5 2>&1`
	echo $rslt
	numlines=`echo "$rslt" | wc -l`
	echo "DEBUG: numlines = $numlines"
	if [ ""$numlines"" -gt 1 ]
	then
		echo
		echo "WARNING: I THINK A REBOOT IS NECESSARY!"
		echo "WARNING: I THINK A REBOOT IS NECESSARY!"
		echo "WARNING: I THINK A REBOOT IS NECESSARY!"
		echo "WARNING: I THINK A REBOOT IS NECESSARY!"
		echo
	fi

	# If all were "perfect", the following line would not be needed. (The module below would have been loaded
	# automatically by the above module.) But we'll add it here, anyway, to cover all bases, and to potentially
	# reveal other issues.  In short, if all went well above, we should see a "File exists" message when we try
	# to load it (again) -
	sudo insmod /lib/modules/4.14.98+/kernel/drivers/w1/slaves/w1_therm.ko 2>&1 | grep -v "File exists"

	sleep 5
	echo
	echo "Check again now."
fi

echo

exit $retval


LSMOD TREE RELATED TO I2C -

w1_gpio                 4566  0
  w1_therm                6679  0
wire                   31600  2 w1_gpio,w1_therm
	cn                      5687  1 wire
	hwmon                  10505  1 wire

i2c_bcm2835             6465  0
i2c_dev                 6706  0


