#!/bin/sh
##################
# do_time - Set system time using the GPS (replaces the NTP daemon with GPS-time)
#
# HISTORICAL INFORMATION -
#
#  2019-06-01  msipin  Pickup (and possibly also set) system time from GPS G[?]ZDA sentences.
#  2019-11-03  msipin  Modified to only rely upon GPRMC, the "minimum recommended set" of data
#                      that ALL GPS devices should send.
#################

# Stratux (or any other device) that is wired directly to UART/serial (needs 60 lines to decode!)
DEV=/dev/serial0


# NOTE NOTE NOTE NOTE -
# NOTE NOTE NOTE NOTE -
#  MAKE SURE that whatever serial port you use here ("DEV") is the same one as is
#  being initialized in /etc/rc.local to 9600 baud.  (E.G. the /etc/rc.local setting
#  initializes the same serial port as the one we intend to use here!)
# NOTE NOTE NOTE NOTE -
# NOTE NOTE NOTE NOTE -


LINES_FROM_GPS=60

# Pickup number of lines to read from the GPS
if [ $# -ge 1 ]
then
	# Pickup number-of-lines to read from GPS before continuing
	LINES_FROM_GPS=$1
fi


# Ensure device is available
ls ${DEV} 2>/dev/null 1>/dev/null
ret_val=$?
#echo "DEBUG: ret_val: $ret_val"
if [ $ret_val != 0 ]
then
	exit 2
fi



# Pickup current time from GPS
head -100 ${DEV} | egrep "^.G[A,B,L,N,P]RMC," | grep ",A," | tail -1 | awk -F"," '{

HR=substr($2,1,2)
MN=substr($2,3,2)
SC=substr($2,5,2)

YY=substr($10,5,2)
MM=substr($10,3,2)
DD=substr($10,1,2)

cmd="date \"+%T +%Y%m%d\" -s \""HR":"MN":"SC" 20"YY"-"MM"-"DD"\""
print(cmd)

system(cmd)

}'


# Set the GPS to high-altitude mode
/usr/local/bin/do_high_alt



exit 0




