#!/bin/sh

data1="Warpig13"
data2=`getpos`
data3=`gettemp`
data4=`tail -5 /usr/local/bin/chipdata.log | grep -v "?" | tail -1 | awk -F"," '{ printf "%d,F ", $4 }'`
### 2020-01-15 msipin Include WiFi link signal strength
###data5=`iwconfig 2>/dev/null | egrep "ESSID:|..:..:..:..:..:.." | grep -v "ESSID:off"`
data5=`iwconfig 2>/dev/null | egrep "ESSID:|..:..:..:..:..:..|dBm" | egrep -v "ESSID:off|Tx-Power"`
data6=`date --rfc-2822`

echo -n ${data1}
echo -n ","
echo -n ${data2}
echo -n ","
echo -n ${data3}
echo -n ","
echo -n ${data4}
echo -n ","
echo -n ${data5}
echo -n ","
echo -n ${data6}

exit 0

