#!/bin/sh

data1="Warpig-VII"
data2=`getpos`
data3=`gettemp`
data4=`iwconfig 2>/dev/null | egrep "ESSID:|..:..:..:..:..:.." | grep -v "ESSID:off"`
data5=`date --rfc-2822`

echo -n ${data1}
echo -n ","
echo -n ${data2}
echo -n ","
echo -n ${data3}
echo -n ","
echo -n ${data4}
echo -n ","
echo -n ${data5}

exit 0

