#!/bin/sh
#########################################
# getDirewolfData - Get data for Direwolf to put at the end of its BEACON string
#########################################

tail -5 /usr/local/bin/tempdata.log | grep -v "?" | tail -1 | awk -F"," '{ print " Temps",$3"/"$7,"F " }'

