#!/bin/sh
#########################################
# getDirewolfData - Get data for Direwolf to put at the end of its BEACON string
#########################################

one=`tail -5 /usr/local/bin/tempdata.log | grep -v "?" | tail -1 | awk -F"," '{ print " ",$3"/"$7"/"$11 }'`
oneB=`tail -5 /usr/local/bin/chipdata.log | grep -v "?" | tail -1 | awk -F"," '{ printf "/%d F ", $4 }'`
two=`date +"%H:%M"`
thr=`cat /usr/local/bin/alt | awk -F"," '{ printf "%d Ft",$1*3.281; }'`

echo ${one}${oneB}${two}" "${thr}

