#!/bin/sh
##################
# gettemp - Return the "last-known-good" temperature data
#
# HISTORICAL INFORMATION -
#
#  2018-02-10  msipin  Created
#################

# All last-known-good data will be obtained from files in the following directory -
LAST_KNOWN_GOOD_DIR=/usr/local/bin

cat ${LAST_KNOWN_GOOD_DIR}/temp

exit 0

