#!/bin/sh
##################
# gpsDaemon - Script intended to be launched in the background, and which
#             repeatedly refreshes the last-known-good position (LAT/LON/ALT)
#             data stored on the filesystem for other programs to pick up later.
#
# HISTORICAL INFORMATION -
#
#  2018-01-21  msipin  Created
#  2018-02-10  msipin  Moved delay out of error condition, and just always do it.
#################

while [ 1 ]
do
    NOW=`date '+%Y-%m-%d,%H:%M:%S'`
    WHERE=`do_gps`
    if [ $? -eq 0 ]
    then
	echo "${WHERE},${NOW}"
    else
    	echo "Error: GPS_ERROR at $NOW"
    fi
    sleep 10
done

exit 0
